### ISSUE TITLE
Language Support: C#

### ISSUE THREAD

**Issue by Phrohdoh** [reproto/reproto#1]
A C# backend powered by [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) would be a good addition IMO.

**Comment by udoprog** [comment]
Agreed, I am not C# person.

The following things are typically a challenge when introducing a new language and framework:

 * How is `datetime` (full iso8601 strings) supported?
 * How is `bytes` (base64-encoded strings) supported?
 * Are optional types supported?
 * Is [field-based polymorphism](https://github.com/reproto/reproto/blob/master/doc/spec.md#interfaces) supported, alternatively how to [shim it in](https://github.com/reproto/reproto/blob/master/backend/src/dynamic_decode.rs#L98)?

Any help with the above would be appreciated.

**Comment by udoprog** [comment]
After some probing with a more knowledgeable friend of mine, most things seem to work all right with `Newtonsoft.Json`.

The one thing I've encountered so far is that the field name for field-based polymorphism is hard-coded to `$type`. And it's unclear how to change its value:
https://stackoverflow.com/questions/9490345/json-net-change-type-field-to-another-name

**Comment by udoprog** [comment]
C# support is now WIP:
https://github.com/reproto/reproto/tree/csharp

It's based of the Java support (most similar), and requires a patched genco to be checked out alongside this project:
https://github.com/udoprog/genco/tree/csharp

**Comment by udoprog** [comment]
Initial support for C# (sans services) passes all integration tests now, you can take it for a spin at https://reproto.github.io
