### ISSUE TITLE
Add `#[allow(non_camel_case_types)]` when emulating nested types in Rust

### ISSUE THREAD

**Issue by idanarye** [reproto/reproto#3]
Since Rust does not support nested struct declarations, reproto is representing them as regular top-level structs named `Outer_Inner`:

```rust
$ cat src/types.reproto 
type Foo {
  type Bar {
  }
}
$ reproto compile rust --path src --out generated --package types
$ cat generated/types.rs 
#[derive(Serialize, Deserialize, Debug)]
pub struct Foo {
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Foo_Bar {
}
```

The problem is that the Rust compiler enforces identifier style conventions, and will emit a warning:
```
warning: type `Foo_Bar` should have a camel case name such as `FooBar`
```

To avoid these warnings, please make the Rust backend starp a `#[allow(non_camel_case_types)]` on top of the structs when it emits these emulated nested types.

Actually - since the protocol may have not been created with Rust in mind and may have unrusty names to begin with, it may be best to always emit these attributes. This applies for fields too(even more common, since it's common to make them have camelCase names) - so you should also add a `#[allow(non_snake_case)]`

Or, just emit this at the top of the file:
```rust
#![allow(non_camel_case_types, non_snake_case)]
```

**Comment by coder543** [comment]
Or it could just emit the name `FooBar` instead of `Foo_Bar`, maybe?

**Comment by udoprog** [comment]
Thanks!

I've been meaning to fix this, but just started ignoring it instead.

`FooBar` would cause conflicts in the generated code with declarations which are actually called `FooBar`, consider:

```reproto
type Foo {
  /// Would also be `FooBar` in rust.
  type Bar {
  }
}

/// Would be `FooBar` in rust.
type FooBar {
}
```

I've setup a PR to remove underscore as a legal part of a type identifier (I didn't even remember it was legal to begin with, and I've never used). This also suppresses the compile-time warning.
